version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./front:/var/www/html
      - ./back:/var/www/html/back
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./BDD/MCD_ddl.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data: 