version: '3.8'

services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/var/www/html
    environment:
      - BACKEND_URL=http://back
    networks:
      - app_network
    depends_on:
      - back

  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./back:/var/www/html
      - ./BDD/MCD_ddl.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data: 