-- Generated by Mocodo 4.3.2
CREATE TABLE
  MATIERE (
    PRIMARY KEY (id_matiere),
    id_matiere INT AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL
  );

CREATE TABLE
  CLASSE (
    PRIMARY KEY (id_classe),
    id_classe INT AUTO_INCREMENT,
    nom_classe VARCHAR(255) NOT NULL,
    niveau VARCHAR(50) NOT NULL,
    numero VARCHAR(50) NOT NULL
  );

CREATE TABLE
  PROF (
    PRIMARY KEY (id_prof),
    id_prof INT AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    matiere INT,
    FOREIGN KEY (matiere) REFERENCES MATIERE (id_matiere)
  );

CREATE TABLE
  USER (
    PRIMARY KEY (id_user),
    id_user INT AUTO_INCREMENT,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    classe INT,
    FOREIGN KEY (classe) REFERENCES CLASSE (id_classe)
  );

CREATE TABLE
  EXAM (
    PRIMARY KEY (id_exam),
    id_exam INT AUTO_INCREMENT,
    titre VARCHAR(255) NOT NULL,
    matiere INT NOT NULL,
    classe INT NOT NULL,
    FOREIGN KEY (matiere) REFERENCES MATIERE (id_matiere),
    FOREIGN KEY (classe) REFERENCES CLASSE (id_classe)
  );

CREATE TABLE
  NOTES (
    PRIMARY KEY (id_note),
    id_note INT AUTO_INCREMENT,
    note DECIMAL(4, 2) NOT NULL,
    user INT NOT NULL,
    exam INT NOT NULL,
    FOREIGN KEY (user) REFERENCES USER (id_user),
    FOREIGN KEY (exam) REFERENCES EXAM (id_exam)
  );