name: Deploy PHP App to Azure

on:
  push:
    branches: [ master ]  # Adaptez à votre branche principale si nécessaire
  workflow_dispatch:    # Permet de déclencher le workflow manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Ajustez selon votre version de PHP
        extensions: mbstring, intl, gd, xml, zip, pdo_mysql  # Ajoutez vos extensions PHP nécessaires
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: none
      
    - name: Validate composer.json and composer.lock
      if: hashFiles('composer.json') != ''
      run: composer validate --strict
      
    - name: Install Composer dependencies
      if: hashFiles('composer.json') != ''
      run: composer install --prefer-dist --no-progress --no-dev
      
    # Si vous utilisez NPM pour les assets front-end (optionnel)
    - name: Install npm dependencies
      if: hashFiles('package.json') != ''
      run: npm ci
      
    - name: Build front-end assets
      if: hashFiles('package.json') != ''
      run: npm run production --if-present
      
    # Si vous utilisez un framework comme Laravel, vous pourriez avoir des étapes spécifiques
    - name: Generate application key
      if: contains(hashFiles('artisan'), 'artisan')
      run: php artisan key:generate --force
      
    - name: Cache configuration
      if: contains(hashFiles('artisan'), 'artisan')
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
      
    # Création d'un fichier web.config pour Azure (si nécessaire)
    - name: Create web.config
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <configuration>
          <system.webServer>
            <rewrite>
              <rules>
                <rule name="Imported Rule 1" stopProcessing="true">
                  <match url="^(.*)/$" ignoreCase="false" />
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                  </conditions>
                  <action type="Redirect" redirectType="Permanent" url="/{R:1}" />
                </rule>
                <rule name="Imported Rule 2" stopProcessing="true">
                  <match url="^" ignoreCase="false" />
                  <conditions>
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                  </conditions>
                  <action type="Rewrite" url="index.php" />
                </rule>
              </rules>
            </rewrite>
          </system.webServer>
        </configuration>' > web.config
    
    # Déploiement sur Azure
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-frontend-pa-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
